# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ac3d52176be3fbab5dc0e45c7a852f0c"
name = "hiding-payment-method"
handle = "hiding-payment-method"
application_url = "https://helps-appointments-chubby-sandwich.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "as-testing-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://helps-appointments-chubby-sandwich.trycloudflare.com/auth/callback",
  "https://helps-appointments-chubby-sandwich.trycloudflare.com/auth/shopify/callback",
  "https://helps-appointments-chubby-sandwich.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
